#!/bin/sh
# Renders the freeze audit's classification table from its manifest (ADR 0027).
# The manifest is the trust root for row content; docs/freeze-audit.md's table is
# this script's output, and check-freeze-audit.sh fails if the page and a fresh
# render diverge. Editing the page's table by hand is therefore a check failure.
#
#   sh spike/freeze-audit/render-audit.sh            # to stdout
#   sh spike/freeze-audit/render-audit.sh --check    # compare against the page
#
# The generated region is delimited by markers and carries a do-not-edit line,
# which is the mechanism spike/unknown-rate/count.py already uses to hold
# docs/unknown-rate.md. The first version of this script anchored on the table's
# header row and stopped at the first non-table line instead; that works until
# prose moves, and building a second, weaker mechanism beside an existing one was
# the reinvention a simplify pass found.
#
# Two field-level rules the table's shape depends on:
#   - Every field is escaped for Markdown pipes. A literal `|` in a title would
#     emit a six-cell row while the TSV stayed well-formed and --check stayed
#     green, because the page would be byte-identical to the same malformed
#     render. It matters more in part two, which imports forty-three more titles.
#   - The disposition is always bold; the rationale follows a colon when present
#     ('-' in the manifest means none). The pre-manifest table used three forms
#     for that one field ("defer", "**narrow**: ...", "defer with the recorded
#     reading: ..."); one form is the point of generating it.
set -u
ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd)
MANIFEST="$ROOT/spike/freeze-audit/audit.tsv"
PAGE="$ROOT/docs/freeze-audit.md"
BEGIN_MARK='<!-- BEGIN generated: freeze-audit classification (render-audit.sh) -->'
END_MARK='<!-- END generated: freeze-audit classification -->'
NOTE='_Generated by `sh spike/freeze-audit/render-audit.sh` — do not edit between the markers._'
[ -s "$MANIFEST" ] || { echo "FAIL: manifest missing or empty: $MANIFEST" >&2; exit 1; }

render() {
    printf '%s\n' "$BEGIN_MARK"
    printf '%s\n' "$NOTE"
    printf '%s\n' ''
    printf '%s\n' '| # | what it is | surface | class | resolution |'
    printf '%s\n' '|---|---|---|---|---|'
    awk -F'\t' '
        /^#/ { next }
        $1 == "number" { next }
        NF == 0 { next }
        NF != 8 { printf "FAIL: row %d has %d columns, wanted 8\n", NR, NF > "/dev/stderr"; bad = 1; next }
        {
            for (i = 1; i <= NF; i++) gsub(/\|/, "\\|", $i)
            res = "**" $7 "**"
            if ($8 != "" && $8 != "-") res = res ": " $8
            printf "| #%s | %s | %s — %s | %s | %s |\n", $1, $3, $4, $5, $6, res
        }
        END { if (bad) exit 1 }
    ' "$MANIFEST" || return 1
    printf '%s\n' "$END_MARK"
}

if [ "${1-}" != "--check" ]; then
    render
    exit $?
fi

[ -s "$PAGE" ] || { echo "FAIL: page missing or empty: $PAGE" >&2; exit 1; }

# Each marker must appear exactly once before anything is sliced: a duplicated
# marker would make the slice silently short, and a comparison against a short
# slice is a comparison that passes for the wrong reason.
for mark in "$BEGIN_MARK" "$END_MARK"; do
    n=$(grep -cF -- "$mark" "$PAGE" || true)
    [ "$n" = "1" ] || { echo "FAIL: the page has $n copies of a generated-block marker, wanted 1" >&2; exit 1; }
done

# Cleanup is non-recursive on purpose: `rm -rf` on a directory is intercepted by
# this developer's own guard tooling, which left the directory behind AND printed
# into this script's output. The fix for one problem introduced another on the
# machine the script is meant to be run by hand on.
tmp=$(mktemp -d) || { echo "FAIL: cannot create a temp directory" >&2; exit 1; }
cleanup_tmp() { rm -f "$tmp"/* 2>/dev/null; rmdir "$tmp" 2>/dev/null; }
trap cleanup_tmp EXIT HUP INT TERM

got="$tmp/page"
want="$tmp/render"
awk -v b="$BEGIN_MARK" -v e="$END_MARK" \
    'index($0, b) { inside = 1 } inside { print } inside && index($0, e) { exit }' \
    "$PAGE" > "$got" || { echo "FAIL: could not slice the generated block from the page" >&2; exit 1; }
render > "$want" || exit 1

if ! cmp -s "$got" "$want"; then
    echo "FAIL: the page's generated block is not a fresh render of the manifest (< page, > render):"
    diff "$got" "$want" | sed 's/^/  /'
    exit 1
fi

lines=$(grep -c . "$want" || true)
echo "ok   the page's generated block is byte-identical to a fresh render ($lines lines)"
