#!/bin/sh
# Renders both of the freeze audit's tables from its manifest (ADR 0027).
# The manifest is the trust root for row content; docs/freeze-audit.md's tables are
# this script's output, and check-freeze-audit.sh fails if the page and a fresh
# render diverge. Editing either table by hand is therefore a check failure.
#
#   sh spike/freeze-audit/render-audit.sh            # both blocks to stdout
#   sh spike/freeze-audit/render-audit.sh --check    # compare against the page
#
# TWO BLOCKS, not one. The active table and the resolved table are separated on the
# page by prose that is held by review rather than generated, so each has its own
# marker pair. Until this sweep the resolved table was hand-written and the gate
# counted active rows only — seventeen rows of adjudication history that nothing
# checked. Migrating them is what showed the manifest's disposition enum had been
# written from the thirteen active rows alone (it had no room for 'document' on a
# class-C row, for 'measured-already-fixed' outside class A, or for a duplicate).
#
# The generated regions are delimited by markers and carry a do-not-edit line,
# which is the mechanism spike/unknown-rate/count.py already uses to hold
# docs/unknown-rate.md.
#
# Field-level rules the tables' shape depends on:
#   - Every field is escaped for Markdown pipes. A literal `|` in a title would
#     emit a six-cell row while the TSV stayed well-formed and --check stayed
#     green, because the page would be byte-identical to the same malformed
#     render. With a hundred and thirteen rows imported from tracker text this is
#     no longer hypothetical.
#   - The disposition is always bold; the rationale follows a colon when present
#     ('-' in the manifest means none).
#   - The surface cell says which axis it is reporting. An active row's entry is a
#     FORECAST (what resolving the issue as filed would move); a resolved row's is
#     a MEASUREMENT (which recorded change its resolution caused). They were one
#     column in the first draft of this schema, which hid that they are different
#     predicates and lost four of the window's five closed-set additions.
#   - `none` renders as "no attributed enumerated change", NOT as "no frozen
#     surface moved". It says only that no change in surface-changes.tsv is
#     attributed to this row, and the measurement covers the enumerated sets alone
#     — the input schemas and every field meaning are rung-3 residue (the isError
#     rule is pinned there by mcp-acceptance.sh; see clause-checks.tsv). The first version rendered `none` as "measured: no frozen surface
#     moved", which converted "not measured" into "unchanged" on rows whose
#     subject is exactly what the measurement does not reach (review P1-3).
set -u
ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd)
MANIFEST="$ROOT/spike/freeze-audit/audit.tsv"
# --check takes an optional page path so the gate can point it at a tampered copy:
# a self-falsification that checks the tampered page with a DIFFERENT predicate
# proves only that the tampering happened.
PAGE="${2:-$ROOT/docs/freeze-audit.md}"

A_BEGIN='<!-- BEGIN generated: freeze-audit classification (render-audit.sh) -->'
A_END='<!-- END generated: freeze-audit classification -->'
R_BEGIN='<!-- BEGIN generated: freeze-audit resolved rows (render-audit.sh) -->'
R_END='<!-- END generated: freeze-audit resolved rows -->'
NOTE='_Generated by `sh spike/freeze-audit/render-audit.sh` — do not edit between the markers._'

[ -s "$MANIFEST" ] || { echo "FAIL: manifest missing or empty: $MANIFEST" >&2; exit 1; }

# render_rows <active|resolved>
render_rows() {
    awk -F'\t' -v want="$1" '
        /^#/ { next }
        $1 == "number" { next }
        NF == 0 { next }
        NF != 9 { printf "FAIL: row %d has %d columns, wanted 9\n", NR, NF > "/dev/stderr"; bad = 1; next }
        $2 != want { next }
        {
            for (i = 1; i <= NF; i++) gsub(/\|/, "\\|", $i)
            res = "**" $8 "**"
            if ($9 != "" && $9 != "-") res = res ": " $9
            if (want == "active") {
                num = "#" $1
                surf = "forecast: " $4 " — " $6
            } else {
                num = "~~#" $1 "~~"
                if ($5 == "none")              surf = "no attributed enumerated change — " $6
                else if ($5 == "not-measured") surf = "not measured by this sweep (closed before its window) — " $6
                else                           surf = "measured: " $5 " — " $6
            }
            printf "| %s | %s | %s | %s | %s |\n", num, $3, surf, $7, res
            n++
        }
        END {
            if (bad) exit 1
            if (n == 0) { printf "FAIL: no %s rows in the manifest\n", want > "/dev/stderr"; exit 1 }
        }
    ' "$MANIFEST"
}

render_active() {
    printf '%s\n' "$A_BEGIN"
    printf '%s\n' "$NOTE"
    printf '%s\n' ''
    printf '%s\n' '| # | what it is | surface | class | resolution |'
    printf '%s\n' '|---|---|---|---|---|'
    render_rows active || return 1
    printf '%s\n' "$A_END"
}

render_resolved() {
    printf '%s\n' "$R_BEGIN"
    printf '%s\n' "$NOTE"
    printf '%s\n' ''
    printf '%s\n' '| issue | what it says | surface | class | resolution |'
    printf '%s\n' '|---|---|---|---|---|'
    render_rows resolved || return 1
    printf '%s\n' "$R_END"
}

if [ "${1-}" != "--check" ]; then
    render_active || exit 1
    printf '%s\n' ''
    render_resolved || exit 1
    exit 0
fi

[ -s "$PAGE" ] || { echo "FAIL: page missing or empty: $PAGE" >&2; exit 1; }

# Each marker must appear exactly once before anything is sliced: a duplicated
# marker would make the slice silently short, and a comparison against a short
# slice is a comparison that passes for the wrong reason. This caught a real
# double-install of the block on its first use.
for mark in "$A_BEGIN" "$A_END" "$R_BEGIN" "$R_END"; do
    n=$(grep -cF -- "$mark" "$PAGE" || true)
    [ "$n" = "1" ] || { echo "FAIL: the page has $n copies of a generated-block marker, wanted 1: $mark" >&2; exit 1; }
done

# Cleanup is non-recursive on purpose: `rm -rf` on a directory is intercepted by
# this developer's own guard tooling, which left the directory behind AND printed
# into this script's output.
tmp=$(mktemp -d) || { echo "FAIL: cannot create a temp directory" >&2; exit 1; }
cleanup_tmp() { rm -f "$tmp"/* 2>/dev/null; rmdir "$tmp" 2>/dev/null; }
trap cleanup_tmp EXIT HUP INT TERM

slice() {  # slice <begin> <end> ; the page's block, inclusive
    awk -v b="$1" -v e="$2" \
        'index($0, b) { inside = 1 } inside { print } inside && index($0, e) { exit }' "$PAGE"
}

status=0
for which in active resolved; do
    if [ "$which" = active ]; then
        slice "$A_BEGIN" "$A_END" > "$tmp/page" || { echo "FAIL: could not slice the active block" >&2; exit 1; }
        render_active > "$tmp/render" || exit 1
    else
        slice "$R_BEGIN" "$R_END" > "$tmp/page" || { echo "FAIL: could not slice the resolved block" >&2; exit 1; }
        render_resolved > "$tmp/render" || exit 1
    fi
    if ! cmp -s "$tmp/page" "$tmp/render"; then
        echo "FAIL: the page's $which block is not a fresh render of the manifest (< page, > render):"
        diff "$tmp/page" "$tmp/render" | sed 's/^/  /' | head -40
        status=1
    else
        lines=$(grep -c . "$tmp/render" || true)
        echo "ok   the page's $which block is byte-identical to a fresh render ($lines lines)"
    fi
done
exit $status
