#!/bin/sh
# check-ledger-prose.sh — the cohort ledger counts these pages state in prose are
# recomputed from the ledgers and the defines on disk (#342).
#
# Why this exists: docs/unknown-rate.md draws a line down its own middle. Everything
# between the results markers is regenerated by count.py and compared byte for byte, and
# the page says so. The prose outside them is held by review — PRD.md's criterion-4
# paragraph used to say that in as many words. Five counts sit in that unheld half and
# describe a set that moves whenever a cohort closes: how many defines were sorted, how
# many entered the corpus, how many each of the two other ledgers holds, and their sum.
# The ledgers themselves cannot drift from the repository (count.py's check_ledgers holds
# union, disjointness and successor existence). What can drift is the pages' description
# of them, and the direction is the bad one: a reader asking whether the corpus is
# complete reads the prose, not the TSVs.
#
# Contract, in both directions:
#   * every figure below is read from the page and compared against count.py's own sets.
#     The numbers are spelled as words, so a small numeral table converts them
#   * a word this table does not know is a FAILURE, not a skip. The table stops at forty
#     and the page already carries `twenty-eight` six times; growing past it must be
#     loud rather than silent
#   * an anchor that no longer matches is a FAILURE. A prose edit that moves a sentence
#     must not quietly take the check with it — this is the one failure mode a
#     grep-shaped check has, and it is why the anchors are sentence fragments rather
#     than line numbers
#   * the two sides are not BOTH empty. Two empty sets agree, and that agreement is what
#     a broken extractor also produces (the shape check-upstream-ledger.sh names for the
#     same reason), so it is BROKEN rather than ok
#
# Not the check ADR 0039 declined. That ruling is about figures QUOTED from other records —
# `docs/kill-criteria-review.md` and `docs/target-classes.md` copying numbers out of RESULTS
# and RUNLOG pages — and its reason is that "a figure check comparing a quotation against an
# unheld source would be comparing two hand-written things and calling one of them the
# truth". These counts have a source that is not hand-written prose: three TSVs and a glob
# over the committed tree, already held against each other by count.py's check_ledgers. One
# side of this comparison is machine-readable and gated; that is the difference, and it is
# why this does not reopen #357.
#
# The counts come from `count.py ledger-sizes` rather than from a shell reimplementation.
# "A committed cohort define" is defined by one glob in count.py; a second copy here
# would drift the first time a revision directory appeared or a non-toml file landed
# under an `ops/`, and the two would disagree with nothing to notice it.
#
# Sunset, both recorded on the page itself: delete this script when the pages stop
# stating these counts in prose, or when the counts move inside the generated block —
# there the byte comparison already holds them and this would be a second gate on one
# fact.

set -eu

root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
fails=0
figures_read=0
# Seven on one page, four on the other.
ledger_figures=11
# Plus the two sentences that say so: each page states how many figures this check reads,
# and that number is a figure like any other. Without them, raising the count would leave
# both pages describing a check that no longer matches — the shape #342 exists to close,
# reproduced in the paragraph explaining the close (review).
expected_figures=$((ledger_figures + 2))

fail() {
    echo "FAIL $*" >&2
    fails=$((fails + 1))
}

# Spelled numerals, including the hyphenated compounds this page uses. Deliberately
# finite: a word outside the table is reported, never treated as zero or skipped.
word_num() {
    case "$1" in
    one) echo 1 ;;            two) echo 2 ;;            three) echo 3 ;;
    four) echo 4 ;;           five) echo 5 ;;           six) echo 6 ;;
    seven) echo 7 ;;          eight) echo 8 ;;          nine) echo 9 ;;
    ten) echo 10 ;;           eleven) echo 11 ;;        twelve) echo 12 ;;
    thirteen) echo 13 ;;      fourteen) echo 14 ;;      fifteen) echo 15 ;;
    sixteen) echo 16 ;;       seventeen) echo 17 ;;     eighteen) echo 18 ;;
    nineteen) echo 19 ;;      twenty) echo 20 ;;        twenty-one) echo 21 ;;
    twenty-two) echo 22 ;;    twenty-three) echo 23 ;;  twenty-four) echo 24 ;;
    twenty-five) echo 25 ;;   twenty-six) echo 26 ;;    twenty-seven) echo 27 ;;
    twenty-eight) echo 28 ;;  twenty-nine) echo 29 ;;   thirty) echo 30 ;;
    thirty-one) echo 31 ;;    thirty-two) echo 32 ;;    thirty-three) echo 33 ;;
    thirty-four) echo 34 ;;   thirty-five) echo 35 ;;   thirty-six) echo 36 ;;
    thirty-seven) echo 37 ;;  thirty-eight) echo 38 ;;  thirty-nine) echo 39 ;;
    forty) echo 40 ;;
    *) return 1 ;;
    esac
}

# figure <label> <file> <sed-expression> <expected>
#
# The sed expression captures the numeral out of its own sentence. A miss is an anchor
# that moved, which is reported rather than skipped.
figure() {
    _label=$1
    _file=$2
    _expr=$3
    _want=$4
    _matches=$(sed -n "$_expr" "$_file")
    _hits=$(printf '%s' "$_matches" | grep -c . || true)
    if [ "$_hits" -gt 1 ]; then
        fail "$_label: the anchor matches $_hits lines in $(basename "$_file") — the figure this reads is no longer the one it names"
        return 0
    fi
    _raw=$(printf '%s\n' "$_matches" | head -1)
    if [ -z "$_raw" ]; then
        fail "$_label: the sentence this check reads is no longer in $(basename "$_file") — the anchor moved, so the figure was not checked"
        return 0
    fi
    figures_read=$((figures_read + 1))
    _lower=$(printf '%s' "$_raw" | tr 'A-Z' 'a-z')
    if ! _got=$(word_num "$_lower"); then
        fail "$_label: '$_raw' is not a numeral this check knows (the table stops at forty)"
        return 0
    fi
    if [ "$_got" != "$_want" ]; then
        fail "$_label: the page says $_raw ($_got), the ledgers say $_want"
        return 0
    fi
    echo "ok   $_label: $_raw ($_got)"
}

# run_check <pages-root> [data-root]
#
# Two roots, because the selftest mutates pages and not ledgers. Copying the cohort trees
# into a scratch just to leave them untouched would make the scratch large enough that
# clearing it needs a recursive sweep, and the shape this repository uses is a named
# removal of exactly what was put there.
run_check() {
    _root=$1
    _data=${2:-$1}
    _sizes=$(python3 "$_data/spike/unknown-rate/count.py" ledger-sizes --root "$_data")
    n_sorted=""; n_corpus=""; n_sup=""; n_exc=""; n_rem=""
    for _kv in $_sizes; do
        case "$_kv" in
        sorted=*) n_sorted=${_kv#sorted=} ;;
        corpus=*) n_corpus=${_kv#corpus=} ;;
        superseded=*) n_sup=${_kv#superseded=} ;;
        excluded=*) n_exc=${_kv#excluded=} ;;
        remaining=*) n_rem=${_kv#remaining=} ;;
        esac
    done
    if [ -z "$n_sorted" ] || [ -z "$n_corpus" ] || [ -z "$n_sup" ] || [ -z "$n_exc" ] || [ -z "$n_rem" ]; then
        fail "count.py ledger-sizes did not print all five counts: $_sizes"
        return 0
    fi

    _ur=$_root/docs/unknown-rate.md
    _prd=$_root/PRD.md

    # docs/unknown-rate.md — three sentences, seven figures.
    figure "sorted (unknown-rate)" "$_ur" \
        's/.*[^A-Za-z-]\([A-Za-z-]\{1,\}\) further defines were committed.*/\1/p' "$n_sorted"
    figure "corpus (unknown-rate)" "$_ur" \
        's/.*[^A-Za-z-]\([A-Za-z-]\{1,\}\) enter the corpus as generation.*/\1/p' "$n_corpus"
    figure "superseded (unknown-rate)" "$_ur" \
        's/.*[^A-Za-z-]\([A-Za-z-]\{1,\}\) are recorded in `supersession.tsv`.*/\1/p' "$n_sup"
    figure "excluded (unknown-rate)" "$_ur" \
        's/.*[^A-Za-z-]\([A-Za-z-]\{1,\}\) in `class-exclusions.tsv` as targets.*/\1/p' "$n_exc"
    figure "remaining (unknown-rate)" "$_ur" \
        's/.*remaining \([A-Za-z-]\{1,\}\) cohort defines are in.*/\1/p' "$n_rem"
    figure "superseded restated (unknown-rate)" "$_ur" \
        's/.*`supersession.tsv` (\([A-Za-z-]\{1,\}\)).*/\1/p' "$n_sup"
    figure "excluded restated (unknown-rate)" "$_ur" \
        's/.*`class-exclusions.tsv` (\([A-Za-z-]\{1,\}\)).*/\1/p' "$n_exc"

    # PRD.md — one sentence, four figures, in the same paragraph whose parenthesis says
    # which half of the page the gate holds.
    figure "sorted (PRD)" "$_prd" \
        's/.*[^A-Za-z-]\([A-Za-z-]\{1,\}\) cohort defines committed since g1.*/\1/p' "$n_sorted"
    figure "corpus (PRD)" "$_prd" \
        's/.*[^A-Za-z-]\([A-Za-z-]\{1,\}\) into the corpus,.*/\1/p' "$n_corpus"
    figure "superseded (PRD)" "$_prd" \
        's/.*[^A-Za-z-]\([A-Za-z-]\{1,\}\) superseded by later revisions.*/\1/p' "$n_sup"
    figure "excluded (PRD)" "$_prd" \
        's/.*[^A-Za-z-]\([A-Za-z-]\{1,\}\) outside the supported classes.*/\1/p' "$n_exc"

    # The two sentences that describe this check, holding their own arithmetic.
    figure "self-count (unknown-rate)" "$_ur" \
        's/.*Those \([A-Za-z-]\{1,\}\) figures are recomputed.*/\1/p' "$ledger_figures"
    figure "self-count (PRD)" "$_prd" \
        's/.*— \([A-Za-z-]\{1,\}\) in all, read from both pages.*/\1/p' "$ledger_figures"

    # Both sides empty is agreement a broken reader also produces.
    if [ "$n_sorted" = "0" ] && [ "$figures_read" = "0" ]; then
        fail "BROKEN: no cohort defines on disk and no figure read from either page — two empty sets agree, and so does a reader that stopped working"
    fi
}

if [ "${1:-}" = "--selftest" ]; then
    # Each figure gets its own red, and so do the two failure modes a grep-shaped check
    # has. A fixture-shaped proof is not available here — the pages this reads are the
    # real ones — so the proof is a scratch copy, mutated one figure at a time.
    #
    # The proofs are COUNTED. The first cut of this selftest reported fifteen and had run
    # thirteen: one mutation depended on a recursive remove that did not happen, the copy
    # kept its cohorts, and the assertion passed on a message from a different predicate.
    # A proof that is not counted is a proof that can quietly not happen.
    st_want=18
    st_ran=0
    st_fails=0

    # Named removal rather than rm -rf, the shape check-upstream-ledger.sh uses: this
    # tree holds exactly the files put into it, and naming them means a stray path
    # cannot be swept up by a wildcard.
    st_clean() {
        rm -f "$1/docs/unknown-rate.md" "$1/docs/unknown-rate.md.bak" "$1/PRD.md" \
              "$1/PRD.md.bak" "$1/spike/unknown-rate/count.py" \
              "$1/spike/unknown-rate/corpus.tsv" \
              "$1/spike/unknown-rate/supersession.tsv" \
              "$1/spike/unknown-rate/class-exclusions.tsv" 2>/dev/null || true
        rmdir "$1/spike/unknown-rate" "$1/spike" "$1/docs" "$1" 2>/dev/null || true
    }

    tmp=$(mktemp -d "${TMPDIR:-/tmp}/ledger-prose-selftest-XXXXXX")
    bare=$(mktemp -d "${TMPDIR:-/tmp}/ledger-prose-bare-XXXXXX")
    trap 'st_clean "$tmp"; st_clean "$bare"' EXIT INT TERM

    mkdir -p "$tmp/docs" "$bare/docs" "$bare/spike/unknown-rate"
    cp "$root/docs/unknown-rate.md" "$tmp/docs/unknown-rate.md"
    cp "$root/PRD.md" "$tmp/PRD.md"

    # The empty-versus-empty tree is built empty rather than emptied: no cohorts copied,
    # ledgers reduced to their comment headers, pages blank. Emptying a full copy would
    # need a recursive remove, and a remove that silently does not happen turns this
    # proof into agreement between two full sets.
    cp "$root/spike/unknown-rate/count.py" "$bare/spike/unknown-rate/count.py"
    cp "$root/spike/unknown-rate/corpus.tsv" "$bare/spike/unknown-rate/corpus.tsv"
    # `|| true` and then an assertion, rather than either alone: grep exits 1 on no match,
    # and under `set -e` that would end the selftest with no output and no failing proof —
    # red in CI, unreadable as a result. A header that has actually gone missing is a
    # failure with a sentence attached instead.
    for _l in supersession class-exclusions; do
        grep '^#' "$root/spike/unknown-rate/$_l.tsv" > "$bare/spike/unknown-rate/$_l.tsv" || true
        if [ ! -s "$bare/spike/unknown-rate/$_l.tsv" ]; then
            echo "SELFTEST FAIL: $_l.tsv has no comment header to build the empty tree from" >&2
            st_fails=$((st_fails + 1))
        fi
    done
    : > "$bare/docs/unknown-rate.md"
    : > "$bare/PRD.md"

    # st_expect_red <root> <label> <fragment> [expected reds] [data-root]
    #
    # The red count is asserted, not just its existence. check-changelog-block's selftest
    # states the reason for its own four defects — "each of which must redden exactly one
    # clause; a case that reddens two would let one of them rot behind the other" — and a
    # mutation here that reddened two figures would hide whichever one stopped working.
    # The default is one; the cases that legitimately redden more say how many.
    st_expect_red() {
        st_ran=$((st_ran + 1))
        _want_red=${4:-1}
        _out=$(fails=0; figures_read=0; run_check "$1" "${5:-$root}" 2>&1) || true
        _red=$(printf '%s\n' "$_out" | grep -c "^FAIL" || true)
        if [ "$_red" = "0" ]; then
            echo "SELFTEST FAIL $2: the mutation produced no FAIL line" >&2
            st_fails=$((st_fails + 1))
            return 0
        fi
        if [ "$_red" != "$_want_red" ]; then
            echo "SELFTEST FAIL $2: $_red figures went red, wanted $_want_red — a mutation that reddens more than it names lets one of them rot behind another:" >&2
            printf '%s\n' "$_out" | grep "^FAIL" | sed 's/^/     | /' >&2
            st_fails=$((st_fails + 1))
            return 0
        fi
        if ! printf '%s\n' "$_out" | grep -qF "$3"; then
            echo "SELFTEST FAIL $2: red, but not on its own predicate — wanted a line carrying '$3', got:" >&2
            printf '%s\n' "$_out" | grep "^FAIL" | sed 's/^/     | /' >&2
            st_fails=$((st_fails + 1))
        fi
    }
    st_restore() {
        cp "$root/docs/unknown-rate.md" "$tmp/docs/unknown-rate.md"
        cp "$root/PRD.md" "$tmp/PRD.md"
    }
    st_ur() { sed -i.bak "$1" "$tmp/docs/unknown-rate.md" && rm -f "$tmp/docs/unknown-rate.md.bak"; }
    st_prd() { sed -i.bak "$1" "$tmp/PRD.md" && rm -f "$tmp/PRD.md.bak"; }

    # Green first: the copy must pass before any mutation means anything.
    st_ran=$((st_ran + 1))
    _green=$(fails=0; figures_read=0; run_check "$tmp" "$root" 2>&1) || true
    if printf '%s\n' "$_green" | grep -q "^FAIL"; then
        echo "SELFTEST FAIL: the unmutated copy is not green:" >&2
        printf '%s\n' "$_green" | grep "^FAIL" | sed 's/^/     | /' >&2
        st_fails=$((st_fails + 1))
    fi

    # Eleven figures, one at a time. `seven` is the right answer to none of them.
    st_ur 's/Eighteen further defines were committed/Seven further defines were committed/'
    st_expect_red "$tmp" "sorted (unknown-rate)" "sorted (unknown-rate): the page says"
    st_restore
    st_ur 's/eight enter the corpus as generation/seven enter the corpus as generation/'
    st_expect_red "$tmp" "corpus (unknown-rate)" "corpus (unknown-rate): the page says"
    st_restore
    st_ur 's/six are recorded in `supersession.tsv`/seven are recorded in `supersession.tsv`/'
    st_expect_red "$tmp" "superseded (unknown-rate)" "superseded (unknown-rate): the page says"
    st_restore
    st_ur 's/four in `class-exclusions.tsv` as targets/seven in `class-exclusions.tsv` as targets/'
    st_expect_red "$tmp" "excluded (unknown-rate)" "excluded (unknown-rate): the page says"
    st_restore
    st_ur 's/remaining ten cohort defines are in/remaining seven cohort defines are in/'
    st_expect_red "$tmp" "remaining (unknown-rate)" "remaining (unknown-rate): the page says"
    st_restore
    st_ur 's/`supersession.tsv` (six)/`supersession.tsv` (seven)/'
    st_expect_red "$tmp" "superseded restated" "superseded restated (unknown-rate): the page says"
    st_restore
    st_ur 's/`class-exclusions.tsv` (four)/`class-exclusions.tsv` (seven)/'
    st_expect_red "$tmp" "excluded restated" "excluded restated (unknown-rate): the page says"
    st_restore
    st_prd 's/eighteen cohort defines committed since g1/seven cohort defines committed since g1/'
    st_expect_red "$tmp" "sorted (PRD)" "sorted (PRD): the page says"
    st_restore
    st_prd 's/eight into the corpus,/seven into the corpus,/'
    st_expect_red "$tmp" "corpus (PRD)" "corpus (PRD): the page says"
    st_restore
    st_prd 's/six superseded by later revisions/seven superseded by later revisions/'
    st_expect_red "$tmp" "superseded (PRD)" "superseded (PRD): the page says"
    st_restore
    st_prd 's/four outside the supported classes/seven outside the supported classes/'
    st_expect_red "$tmp" "excluded (PRD)" "excluded (PRD): the page says"
    st_restore
    st_ur 's/Those eleven figures are recomputed/Those seven figures are recomputed/'
    st_expect_red "$tmp" "self-count (unknown-rate)" "self-count (unknown-rate): the page says"
    st_restore
    st_prd 's/— eleven in all, read from both pages/— seven in all, read from both pages/'
    st_expect_red "$tmp" "self-count (PRD)" "self-count (PRD): the page says"
    st_restore

    # The anchor moving — the failure a grep-shaped check would otherwise take as agreement.
    st_ur 's/further defines were committed/further defines landed/'
    st_expect_red "$tmp" "anchor moved" "the anchor moved"
    st_restore

    # A numeral outside the table.
    st_ur 's/Eighteen further defines were committed/Fifty further defines were committed/'
    st_expect_red "$tmp" "numeral outside the table" "is not a numeral this check knows"
    st_restore

    # The guards this check grew during review get their own reds, for the reason this
    # whole script exists: CLAUDE.md asks that every new check be seen red once, and a
    # guard proven only by the author having tried it by hand is the shape that put
    # thirty-six dead predicates inside count.py.
    #
    # An anchor that matches twice: the figure read is no longer the one named.
    awk '{print} /further defines were committed/{print}' "$tmp/docs/unknown-rate.md" > "$tmp/docs/dup.md"
    mv "$tmp/docs/dup.md" "$tmp/docs/unknown-rate.md"
    st_expect_red "$tmp" "anchor matches twice" "the anchor matches 2 lines"
    st_restore

    # Both sides empty, in the tree built empty.
    # Twelve reds, not one: with both pages blank every anchor is gone, so all eleven
    # figures report a moved anchor and BROKEN is the twelfth. Stating the number is the
    # point — it says this proof knows what it destroyed.
    st_expect_red "$bare" "both sides empty" "BROKEN" 14 "$bare"

    if [ "$st_ran" != "$st_want" ]; then
        echo "SELFTEST FAIL: ran $st_ran proofs, wanted $st_want — a proof did not happen" >&2
        st_fails=$((st_fails + 1))
    fi
    if [ "$st_fails" -gt 0 ]; then
        echo "check-ledger-prose --selftest: $st_fails of $st_want proofs did not hold" >&2
        exit 1
    fi
    echo "ok   check-ledger-prose --selftest: $st_ran proofs — one green copy, thirteen figures each red on its own predicate, a moved anchor, a doubled anchor, an unknown numeral, and both sides empty"
    exit 0
fi

run_check "$root"
if [ "$fails" -gt 0 ]; then
    echo "check-ledger-prose: $fails figure(s) disagree with the ledgers" >&2
    exit 1
fi
if [ "$figures_read" != "$expected_figures" ]; then
    echo "FAIL check-ledger-prose: read $figures_read figures, expected $expected_figures — a figure was dropped from this check rather than from the pages" >&2
    exit 1
fi
echo "ok   check-ledger-prose: $figures_read figures across docs/unknown-rate.md and PRD.md match the three ledgers and the defines on disk"
