#!/bin/sh
# Cohort-3 poetry revision-2 setup: the project (manifest + a lockfile
# generated by poetry's own `lock`). Manifest bytes are the primary's
# frozen block, unchanged; there is no outside-root fixture (the
# operation takes none). The ambient cache/config are created here and
# shared across worlds (outside the snapshot); the `poetry lock` run
# also warms them, so world 1 and world N meet the same ambient shape.
set -eu
P=/tmp/cohort3/poetry-r2
rm -rf "$P/state"
mkdir -p "$P/state" "$P/pcache" "$P/pconfig" "$P/home"
cat > "$P/state/pyproject.toml" <<'EOF'
[project]
name = "app"
version = "0.1.0"
requires-python = ">=3.13"

[tool.poetry]
package-mode = false
EOF
export POETRY_CACHE_DIR="$P/pcache" POETRY_CONFIG_DIR="$P/pconfig"
export PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring
export POETRY_VIRTUALENVS_CREATE=false
export HOME="$P/home"
poetry -C "$P/state" lock
