#!/bin/sh
# Cut transcripts/probes/open-flags.txt out of the screens' full strace captures (not committed:
# 6.8 MB for the first pass alone; screen.sh, screen2.sh and screen3.sh regenerate them).
#   excerpts.sh <dir holding screen/, screen2/, screen3/> > open-flags.txt
# The first version of this file was cut by hand and annotated a count its excerpt did not show;
# the review of this record caught it.
set -u
B=$1
ex() {  # ex <capture> <title> <extended regex over the whole line>
  echo; echo "## $1 — $2"
  grep -n -E "$3" "$B/$1" | grep -v -E 'O_RDONLY|ENOENT|host_virtiofs' | cut -c1-230
}
echo "# Excerpts from the screens' strace captures (strace -f -y), the lines RESULTS.md cites."
echo "# Generated by apparatus/excerpts.sh from captures that are not committed."
ex screen/bun.strace "package.json: the probe open, then the rewrite" 'openat\(.*strace/bun/package\.json|write\([0-9]+</localrun/st/strace/bun/package\.json>'
ex screen/markdownlint.strace "README.md: the rewrite" 'openat\(.*markdownlint/README\.md|write\([0-9]+<.*README\.md>'
ex screen2/ninja.strace "out.txt (cp, pid 32) and .ninja_log (ninja, pid 30)" 'openat\(.*"out\.txt"|copy_file_range\(|ioctl\(.*out\.txt|openat\(.*\.ninja_log.*O_WRONLY|write\([0-9]+<.*\.ninja_log>'
ex screen3/gjf.strace "A.java: the rewrite; and the one other tid strace -y ties to the state directory" 'openat\(.*gjf/A\.java|write\([0-9]+<.*A\.java>|unlinkat\(.*hsperfdata'
ex screen3/xz.strace "f.bin.xz: the create, the fsyncs, the closes, the unlink" 'openat\(.*f\.bin\.xz|fsync\(|close\((5|6|7)</localrun/st/strace/xz|unlinkat\(.*xz/f\.bin"'
echo "  write(7<…f.bin.xz>) calls in the capture: $(grep -c 'write(7</localrun/st/strace/xz/f.bin.xz>' "$B/screen3/xz.strace"), from tid(s): $(grep 'write(7</localrun/st/strace/xz/f.bin.xz>' "$B/screen3/xz.strace" | awk '{print $1}' | sort -u | tr '\n' ' ')(the process's first thread is 223)"
