#!/bin/sh
# Fetch the pinned release artifacts the cohort-3 image copies in (see
# Dockerfile). This runs on the HOST, not in the container, for the reason
# cohort 2 measured (spike/cohort2/fetch-artifacts.sh): the development
# machine sits behind a TLS-intercepting proxy whose CA a stock Debian
# container does not trust, so in-container pip/curl fail certificate
# verification. Downloads run host-side; every artifact is verified against
# a pin that upstream published, and the Dockerfile re-verifies the copies.
#
# Pins:
#   - rust: sha256 from the Rust channel manifest
#     (https://static.rust-lang.org/dist/channel-rust-stable.toml, read
#     2026-08-22; stable = 1.98.0, released 2026-08-18). The manifest is
#     rustup's own source of truth for the artifact. The combined
#     standalone tarball bundles rustfmt-preview (measured in its
#     `components` file), so no separate rustfmt artifact exists here.
#   - Python packages: pins-wheels.txt + pins-sdist.txt, a split of
#     pins-all.txt — a cross-platform lock generated by uv (command in that
#     file's header; behind this proxy uv needs --system-certs) with
#     --generate-hashes, so every hash is PyPI's published one and
#     `pip download --require-hashes` verifies each file. The sdist file
#     exists because exactly two packages in the closure ship no wheel at
#     their locked version (measured 2026-08-22): bibtexparser 1.4.4 and
#     python-doi 0.2.0. Both are pure Python; the Dockerfile builds them
#     with --no-build-isolation against apt's setuptools.
set -eu

here=$(cd "$(dirname "$0")" && pwd)
dest="$here/artifacts"
mkdir -p "$dest" "$dest/wheels"

# The split files must cover the lock exactly — every LINE, hashes
# included: the split was produced by partitioning pins-all.txt line by
# line, so the sorted concatenation of the two halves must equal the
# sorted whole. A dropped or edited --hash line fails here, not only a
# changed version pin (the R1 review falsified the earlier name==version
# check against exactly that: a deleted hash line passed it). (Temp
# files, not process substitution: this script is /bin/sh, and <(...) is
# a bashism.)
chk=$(mktemp -d) || exit 1
trap 'rm -f "$chk/split" "$chk/all"; rmdir "$chk" 2>/dev/null' EXIT
sort "$here/pins-wheels.txt" "$here/pins-sdist.txt" > "$chk/split"
sort "$here/pins-all.txt" > "$chk/all"
if ! cmp -s "$chk/split" "$chk/all"; then
    echo "FAIL: pins-wheels.txt + pins-sdist.txt do not cover pins-all.txt exactly (line-level, hashes included)" >&2
    diff "$chk/split" "$chk/all" >&2 || true
    exit 1
fi

sum() {
    if command -v sha256sum >/dev/null 2>&1; then sha256sum "$1"
    else shasum -a 256 "$1"; fi
}

fetch() {
    name=$1; url=$2; want=$3
    out="$dest/$name"
    if [ -f "$out" ]; then
        got=$(sum "$out" | cut -d' ' -f1)
        [ "$got" = "$want" ] && { echo "ok   $name (cached)"; return 0; }
        echo "stale $name: checksum mismatch, refetching" >&2
        rm -f "$out"
    fi
    curl -fsSL -o "$out" "$url"
    got=$(sum "$out" | cut -d' ' -f1)
    [ "$got" = "$want" ] || { echo "FAIL $name: sha256 $got, wanted $want" >&2; rm -f "$out"; exit 1; }
    echo "ok   $name"
}

fetch rust-1.98.0-aarch64-unknown-linux-gnu.tar.xz \
    "https://static.rust-lang.org/dist/2026-08-20/rust-1.98.0-aarch64-unknown-linux-gnu.tar.xz" \
    ac9283184301aeed06ecc9f5aa4c1be7041e18a1b197b6cb6c5d162d98f566da

# Wheels: cross-platform download for the image's interpreter (Debian trixie
# python3 = 3.13, aarch64 glibc). --require-hashes makes PyPI's published
# hashes the acceptance test for every file; --no-deps because the lock IS
# the closure. The three manylinux tags cover the wheels the lock resolved.
python3 -m pip download --require-hashes --no-deps -r "$here/pins-wheels.txt" \
    --only-binary=:all: --python-version 3.13 --implementation cp \
    --platform manylinux_2_28_aarch64 --platform manylinux_2_17_aarch64 \
    --platform manylinux2014_aarch64 \
    -d "$dest/wheels"

# The two sdist-only packages: platform-independent, same hash discipline.
python3 -m pip download --require-hashes --no-deps -r "$here/pins-sdist.txt" \
    --no-binary=:all: -d "$dest/wheels"

echo "artifacts ready in $dest"
