#!/bin/sh
# Cohort-3 poetry define (P1) setup: the project (manifest + a lockfile
# generated by poetry's own `lock`) and the outside-root path
# dependency. Fixture bytes are the probe plan's, frozen in PROTOCOL.md.
# The ambient cache/config are created here and shared across worlds
# (outside the snapshot); the `poetry lock` run also warms them, so
# world 1 and world N meet the same ambient shape.
set -eu
P=/tmp/cohort3/poetry
rm -rf "$P/state" "$P/deppkg"
mkdir -p "$P/state" "$P/deppkg/deppkg" "$P/pcache" "$P/pconfig" "$P/home"
cat > "$P/state/pyproject.toml" <<'EOF'
[project]
name = "app"
version = "0.1.0"
requires-python = ">=3.13"

[tool.poetry]
package-mode = false
EOF
cat > "$P/deppkg/pyproject.toml" <<'EOF'
[project]
name = "deppkg"
version = "0.1.0"
requires-python = ">=3.13"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
EOF
: > "$P/deppkg/deppkg/__init__.py"
export POETRY_CACHE_DIR="$P/pcache" POETRY_CONFIG_DIR="$P/pconfig"
export PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring
export POETRY_VIRTUALENVS_CREATE=false
poetry -C "$P/state" lock
