[calendars]
[[main]]
path = /tmp/blind2/khal/state

[locale]
local_timezone= UTC
default_timezone= UTC
timeformat= %H:%M
dateformat= %d.%m.
longdateformat= %d.%m.%Y
datetimeformat= %d.%m. %H:%M
longdatetimeformat= %d.%m.%Y %H:%M
