[world]
state = "/s/bat/state"

[define]
operation = ["batcat", "cache", "--build", "--source", "/s/bat/aux/batsrc", "--target", "/s/bat/state"]
check     = "/ap/defines/bat/check.sh"
apparatus = ["env:FAKETIME=@2024-01-01 00:00:00", "preload:libfaketime"]
