#!/bin/sh
# Cut transcripts/probes/open-flags.txt out of the screens' full strace captures, which are not
# committed (apparatus/screen.sh and screen2.sh regenerate them).
#   excerpts.sh <dir holding screen/ and screen2/> > open-flags.txt
set -u
B=$1
ex() {  # ex <capture> <title> <extended regex over the whole line>
  echo; echo "## $1 — $2"
  grep -n -E "$3" "$B/$1" | grep -v -E 'O_RDONLY|ENOENT|host_virtiofs' | cut -c1-230
}
echo "# Excerpts from the screens' strace captures (strace -f -y), the lines RESULTS.md cites."
echo "# Generated by apparatus/excerpts.sh from captures that are not committed."
ex screen/aws.strace "credentials" 'openat\(.*aws/credentials|write\([0-9]+<.*aws/credentials>'
ex screen/hatch.strace "config.toml and its temporary" 'openat\(.*strace/hatch/tmp|write\([0-9]+<.*strace/hatch/tmp|fsync\(|renameat\(.*hatch'
ex screen/nvim.strace "main.shada and main.shada.tmp.a" 'openat\(.*main\.shada\.tmp|unlinkat\(.*main\.shada|renameat\(.*main\.shada|write\([0-9]+<.*main\.shada|fsync\([0-9]+<.*main\.shada'
ex screen2/jbang-java.strace "jbang.properties" 'openat\(.*jbang\.properties|write\([0-9]+<.*jbang\.properties>'
ex screen/pyenv.strace "version" 'openat\(.*pyenv/version"|write\([0-9]+<.*pyenv/version>'
